### ISSUE TITLE
这几行代码看起来是多余的吗？

### ISSUE THREAD

**Issue by nomeqc** [Eleme-IMF/DRDNetworking#17]
DRDAPIManager.m中requestSerializerForAPI: 方法
`NSError *serializationError = nil;
    if (serializationError) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [weakSelf handleFailureWithError:serializationError andAPI:api];
        });
        return nil;
    }
`
if条件永远不成立

**Comment by cendywang** [comment]
感谢您指出这个问题。

代码迁移时忘删了：） 

再次感谢

**Comment by aozhimin** [comment]
#19 去掉了！谢谢

**Comment by aozhimin** [comment]
@Nomeqc #19 去掉了！谢谢
