### ISSUE TITLE
DRDNetworking网络请求的一些看法

### ISSUE THREAD

**Issue by wulongwang** [Eleme-IMF/DRDNetworking#26]
1、DRDNetworking是否可以加入不同环境下的api (线上和线下的快速切换)
2、从DRDGeneralAPI 的setApiResponseObjReformerBlock 这里面处理数据的转换能否不放在控制器内，其实控制器内是不关注数据的转换
3、能否加入一个工具类去统一管理请求的API。
4、结构很清晰，学到内容，谢谢。

**Comment by cendywang** [comment]
@fbi080703 
Hi 非常感谢建议。
1、我们这里的实践是在Config里进行Baseapi进行操作，来进行线上线下转换。
2、这个建议很好，我在下一个版本中会加上。非常感谢
3、这个不是太明白？
4、很开心能帮到您

**Comment by cendywang** [comment]
0.6.1 add reformer delegate for generalAPI
