### ISSUE TITLE
response缺少"text/plain"的类型

### ISSUE THREAD

**Issue by ZenonHuang** [Eleme-IMF/DRDNetworking#32]
今天做微信第三方登录，请求access_token一直报错，后来排查发现是因为"text/plain"类型的缘故。建议在apiResponseAcceptableContentTypes加上。

**Comment by cendywang** [comment]
@zzgo Hi, 抱歉这么晚回复，前段时间有点忙

正如您所说，默认没有加上这个。不过可以在：
- (nullable NSSet *)apiResponseAcceptableContentTypes;

里自定义添加。

下一个版本将根据您的建议添加进默认

感谢pr
