### ISSUE TITLE
请教一个callAPICompletion方法里主线程里回调的问题

### ISSUE THREAD

**Issue by Hanazawa** [Eleme-IMF/DRDNetworking#38]
你好, 最近在简书上看到这个框架, 非常感谢您的开源~
最近尝试学习阅读源代码, 因为在简书上找不到评论的地方, 所以来这边想请教你一个问题
因为AFURLSessionManager默认设置好像是收到返回的请求后, 他会在主线程调用(如果没有设置completionQueue的话)
那在DRDAPIManager的callAPICompletion方法里为什么需要回到主线程呢? 我找了一下DRDAPIManager好像没有设置completionQueue的代码...

**Comment by cendywang** [comment]
@Hanazawa 这里记得当时设计时考虑的问题是在于，很多情况下网络数据返回后都需要去刷新界面上的数据；当然也有小部分概率会放后台来做相应的数据处理。
基于这个在界面刷新数据的考量，因此放到主线程去处理数据返回；如果有需要，可以在callAPICompletion中在自主设定由某个后台线程来处理数据。
